[project]
name = "first-mcp-server"
version = "0.1.0"
requires-python = ">=3.12.3"

dependencies = [
    "fastmcp>=2.3.4",     # ← real server library (gives you FastMCP.method)
    "mcp[cli]>=1.6.0",    # optional — only if you want the CLI in the same env
    "requests>=2.31.0",
]
