# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mcp-linkedin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mukulmcpregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_03211d6e76424ae7b66f05823f581824 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_659f0d9971584af09dda9e2050eee0dc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mukulmcpregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_03211d6e76424ae7b66f05823f581824 }}/mcp-linkedin:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mcp-linkedin'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f3dd5cd8f34d42eb84d0e55f682887ff }}
        images: 'mukulmcpregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_03211d6e76424ae7b66f05823f581824 }}/mcp-linkedin:${{ github.sha }}'